# global settings
title: "SCI des chênes verts"
description: "Building together a new innovative ecosystem for farms"
permalink: "/stories/:title"
url: https://sci-chenes-verts.github.io
relative_permalinks: false

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules"]
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-coffeescript
  - jekyll-remote-theme

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

github:
  is_project_page: false
